export const cardsInfo = [
  {
    category: "clubs",
    card: "2",
    power: "2",
    img: "./cards/2_of_clubs.png",
  },
  {
    category: "diamonds",
    card: "2",
    power: "2",
    img: "./cards/2_of_diamonds.png",
  },
  {
    category: "hearts",
    card: "2",
    power: "2",
    img: "./cards/2_of_hearts.png",
  },
  {
    category: "spades",
    card: "2",
    power: "2",
    img: "./cards/2_of_spades.png",
  },
  { category: "clubs", card: "3", power: "3", img: "./cards/3_of_clubs.png" },
  {
    category: "diamonds",
    card: "3",
    power: "3",
    img: "./cards/3_of_diamonds.png",
  },
  { category: "hearts", card: "3", power: "3", img: "./cards/3_of_hearts.png" },
  { category: "spades", card: "3", power: "3", img: "./cards/3_of_spades.png" },
  { category: "clubs", card: "4", power: "4", img: "./cards/4_of_clubs.png" },
  {
    category: "diamonds",
    card: "4",
    power: "4",
    img: "./cards/4_of_diamonds.png",
  },
  { category: "hearts", card: "4", power: "4", img: "./cards/4_of_hearts.png" },
  { category: "spades", card: "4", power: "4", img: "./cards/4_of_spades.png" },
  { category: "clubs", card: "5", power: "5", img: "./cards/5_of_clubs.png" },
  {
    category: "diamonds",
    card: "5",
    power: "5",
    img: "./cards/5_of_diamonds.png",
  },
  { category: "hearts", card: "5", power: "5", img: "./cards/5_of_hearts.png" },
  { category: "spades", card: "5", power: "5", img: "./cards/5_of_spades.png" },
  { category: "clubs", card: "6", power: "6", img: "./cards/6_of_clubs.png" },
  {
    category: "diamonds",
    card: "6",
    power: "6",
    img: "./cards/6_of_diamonds.png",
  },
  { category: "hearts", card: "6", power: "6", img: "./cards/6_of_hearts.png" },
  { category: "spades", card: "6", power: "6", img: "./cards/6_of_spades.png" },
  { category: "clubs", card: "7", power: "7", img: "./cards/7_of_clubs.png" },
  {
    category: "diamonds",
    card: "7",
    power: "7",
    img: "./cards/7_of_diamonds.png",
  },
  { category: "hearts", card: "7", power: "7", img: "./cards/7_of_hearts.png" },
  { category: "spades", card: "7", power: "7", img: "./cards/7_of_spades.png" },
  { category: "clubs", card: "8", power: "8", img: "./cards/8_of_clubs.png" },
  {
    category: "diamonds",
    card: "8",
    power: "8",
    img: "./cards/8_of_diamonds.png",
  },
  { category: "hearts", card: "8", power: "8", img: "./cards/8_of_hearts.png" },
  { category: "spades", card: "8", power: "8", img: "./cards/8_of_spades.png" },
  { category: "clubs", card: "9", power: "9", img: "./cards/9_of_clubs.png" },
  {
    category: "diamonds",
    card: "9",
    power: "9",
    img: "./cards/9_of_diamonds.png",
  },
  { category: "hearts", card: "9", power: "9", img: "./cards/9_of_hearts.png" },
  { category: "spades", card: "9", power: "9", img: "./cards/9_of_spades.png" },
  {
    category: "clubs",
    card: "10",
    power: "10",
    img: "./cards/10_of_clubs.png",
  },
  {
    category: "diamonds",
    card: "10",
    power: "10",
    img: "./cards/10_of_diamonds.png",
  },
  {
    category: "hearts",
    card: "10",
    power: "10",
    img: "./cards/10_of_hearts.png",
  },
  {
    category: "spades",
    card: "10",
    power: "10",
    img: "./cards/10_of_spades.png",
  },
  {
    category: "clubs",
    card: "J",
    power: "11",
    img: "./cards/jack_of_clubs.png",
  },
  {
    category: "diamonds",
    card: "J",
    power: "11",
    img: "./cards/jack_of_diamonds.png",
  },
  {
    category: "hearts",
    card: "J",
    power: "11",
    img: "./cards/jack_of_hearts.png",
  },
  {
    category: "spades",
    card: "J",
    power: "11",
    img: "./cards/jack_of_spades.png",
  },
  {
    category: "clubs",
    card: "Q",
    power: "12",
    img: "./cards/queen_of_clubs.png",
  },
  {
    category: "diamonds",
    card: "Q",
    power: "12",
    img: "./cards/queen_of_diamonds.png",
  },
  {
    category: "hearts",
    card: "Q",
    power: "12",
    img: "./cards/queen_of_hearts.png",
  },
  {
    category: "spades",
    card: "Q",
    power: "12",
    img: "./cards/queen_of_spades.png",
  },
  {
    category: "clubs",
    card: "K",
    power: "13",
    img: "./cards/king_of_clubs.png",
  },
  {
    category: "diamonds",
    card: "K",
    power: "13",
    img: "./cards/king_of_diamonds.png",
  },
  {
    category: "hearts",
    card: "K",
    power: "13",
    img: "./cards/king_of_hearts.png",
  },
  {
    category: "spades",
    card: "K",
    power: "13",
    img: "./cards/king_of_spades.png",
  },
  {
    category: "clubs",
    card: "A",
    power: "14",
    img: "./cards/ace_of_clubs.png",
  },
  {
    category: "diamonds",
    card: "A",
    power: "14",
    img: "./cards/ace_of_diamonds.png",
  },
  {
    category: "hearts",
    card: "A",
    power: "14",
    img: "./cards/ace_of_hearts.png",
  },
  {
    category: "spades",
    card: "A",
    power: "14",
    img: "./cards/ace_of_spades.png",
  },
];
