export const cardsInfo = [
  { category: "clubs", card: "2", img: "../assets/cards/2_of_clubs.png" },
  { category: "diamonds", card: "2", img: "../assets/cards/2_of_diamonds.png" },
  { category: "hearts", card: "2", img: "../assets/cards/2_of_hearts.png" },
  { category: "spades", card: "2", img: "../assets/cards/2_of_spades.png" },
  { category: "clubs", card: "3", img: "../assets/cards/3_of_clubs.png" },
  { category: "diamonds", card: "3", img: "../assets/cards/3_of_diamonds.png" },
  { category: "hearts", card: "3", img: "../assets/cards/3_of_hearts.png" },
  { category: "spades", card: "3", img: "../assets/cards/3_of_spades.png" },
  { category: "clubs", card: "4", img: "../assets/cards/4_of_clubs.png" },
  { category: "diamonds", card: "4", img: "../assets/cards/4_of_diamonds.png" },
  { category: "hearts", card: "4", img: "../assets/cards/4_of_hearts.png" },
  { category: "spades", card: "4", img: "../assets/cards/4_of_spades.png" },
  { category: "clubs", card: "5", img: "../assets/cards/5_of_clubs.png" },
  { category: "diamonds", card: "5", img: "../assets/cards/5_of_diamonds.png" },
  { category: "hearts", card: "5", img: "../assets/cards/5_of_hearts.png" },
  { category: "spades", card: "5", img: "../assets/cards/5_of_spades.png" },
  { category: "clubs", card: "6", img: "../assets/cards/6_of_clubs.png" },
  { category: "diamonds", card: "6", img: "../assets/cards/6_of_diamonds.png" },
  { category: "hearts", card: "6", img: "../assets/cards/6_of_hearts.png" },
  { category: "spades", card: "6", img: "../assets/cards/6_of_spades.png" },
  { category: "clubs", card: "7", img: "../assets/cards/7_of_clubs.png" },
  { category: "diamonds", card: "7", img: "../assets/cards/7_of_diamonds.png" },
  { category: "hearts", card: "7", img: "../assets/cards/7_of_hearts.png" },
  { category: "spades", card: "7", img: "../assets/cards/7_of_spades.png" },
  { category: "clubs", card: "8", img: "../assets/cards/8_of_clubs.png" },
  { category: "diamonds", card: "8", img: "../assets/cards/8_of_diamonds.png" },
  { category: "hearts", card: "8", img: "../assets/cards/8_of_hearts.png" },
  { category: "spades", card: "8", img: "../assets/cards/8_of_spades.png" },
  { category: "clubs", card: "9", img: "../assets/cards/9_of_clubs.png" },
  { category: "diamonds", card: "9", img: "../assets/cards/9_of_diamonds.png" },
  { category: "hearts", card: "9", img: "../assets/cards/9_of_hearts.png" },
  { category: "spades", card: "9", img: "../assets/cards/9_of_spades.png" },
  { category: "clubs", card: "10", img: "../assets/cards/10_of_clubs.png" },
  {
    category: "diamonds",
    card: "10",
    img: "../assets/cards/10_of_diamonds.png",
  },
  { category: "hearts", card: "10", img: "../assets/cards/10_of_hearts.png" },
  { category: "spades", card: "10", img: "../assets/cards/10_of_spades.png" },
  { category: "clubs", card: "J", img: "../assets/cards/jack_of_clubs.png" },
  {
    category: "diamonds",
    card: "J",
    img: "../assets/cards/jack_of_diamonds.png",
  },
  { category: "hearts", card: "J", img: "../assets/cards/jack_of_hearts.png" },
  { category: "spades", card: "J", img: "../assets/cards/jack_of_spades.png" },
  { category: "clubs", card: "Q", img: "../assets/cards/queen_of_clubs.png" },
  {
    category: "diamonds",
    card: "Q",
    img: "../assets/cards/queen_of_diamonds.png",
  },
  { category: "hearts", card: "Q", img: "../assets/cards/queen_of_hearts.png" },
  { category: "spades", card: "Q", img: "../assets/cards/queen_of_spades.png" },
  { category: "clubs", card: "K", img: "../assets/cards/king_of_clubs.png" },
  {
    category: "diamonds",
    card: "K",
    img: "../assets/cards/king_of_diamonds.png",
  },
  { category: "hearts", card: "K", img: "../assets/cards/king_of_hearts.png" },
  { category: "spades", card: "K", img: "../assets/cards/king_of_spades.png" },
  { category: "clubs", card: "A", img: "../assets/cards/ace_of_clubs.png" },
  {
    category: "diamonds",
    card: "A",
    img: "../assets/cards/ace_of_diamonds.png",
  },
  { category: "hearts", card: "A", img: "../assets/cards/ace_of_hearts.png" },
  { category: "spades", card: "A", img: "../assets/cards/ace_of_spades.png" },
];
