export const cardsInfo = [
  {
    category: "clubs",
    card: "2",
    power: "2",
    img: "./cards/2ofclubs.png",
  },
  {
    category: "diamonds",
    card: "2",
    power: "2",
    img: "./cards/2ofdiamonds.png",
  },
  {
    category: "hearts",
    card: "2",
    power: "2",
    img: "./cards/2ofhearts.png",
  },
  {
    category: "spades",
    card: "2",
    power: "2",
    img: "./cards/2ofspades.png",
  },
  { category: "clubs", card: "3", power: "3", img: "./cards/3ofclubs.png" },
  {
    category: "diamonds",
    card: "3",
    power: "3",
    img: "./cards/3ofdiamonds.png",
  },
  { category: "hearts", card: "3", power: "3", img: "./cards/3ofhearts.png" },
  { category: "spades", card: "3", power: "3", img: "./cards/3ofspades.png" },
  { category: "clubs", card: "4", power: "4", img: "./cards/4ofclubs.png" },
  {
    category: "diamonds",
    card: "4",
    power: "4",
    img: "./cards/4ofdiamonds.png",
  },
  { category: "hearts", card: "4", power: "4", img: "./cards/4ofhearts.png" },
  { category: "spades", card: "4", power: "4", img: "./cards/4ofspades.png" },
  { category: "clubs", card: "5", power: "5", img: "./cards/5ofclubs.png" },
  {
    category: "diamonds",
    card: "5",
    power: "5",
    img: "./cards/5ofdiamonds.png",
  },
  { category: "hearts", card: "5", power: "5", img: "./cards/5ofhearts.png" },
  { category: "spades", card: "5", power: "5", img: "./cards/5ofspades.png" },
  { category: "clubs", card: "6", power: "6", img: "./cards/6ofclubs.png" },
  {
    category: "diamonds",
    card: "6",
    power: "6",
    img: "./cards/6ofdiamonds.png",
  },
  { category: "hearts", card: "6", power: "6", img: "./cards/6ofhearts.png" },
  { category: "spades", card: "6", power: "6", img: "./cards/6ofspades.png" },
  { category: "clubs", card: "7", power: "7", img: "./cards/7ofclubs.png" },
  {
    category: "diamonds",
    card: "7",
    power: "7",
    img: "./cards/7ofdiamonds.png",
  },
  { category: "hearts", card: "7", power: "7", img: "./cards/7ofhearts.png" },
  { category: "spades", card: "7", power: "7", img: "./cards/7ofspades.png" },
  { category: "clubs", card: "8", power: "8", img: "./cards/8ofclubs.png" },
  {
    category: "diamonds",
    card: "8",
    power: "8",
    img: "./cards/8ofdiamonds.png",
  },
  { category: "hearts", card: "8", power: "8", img: "./cards/8ofhearts.png" },
  { category: "spades", card: "8", power: "8", img: "./cards/8ofspades.png" },
  { category: "clubs", card: "9", power: "9", img: "./cards/9ofclubs.png" },
  {
    category: "diamonds",
    card: "9",
    power: "9",
    img: "./cards/9ofdiamonds.png",
  },
  { category: "hearts", card: "9", power: "9", img: "./cards/9ofhearts.png" },
  { category: "spades", card: "9", power: "9", img: "./cards/9ofspades.png" },
  {
    category: "clubs",
    card: "10",
    power: "10",
    img: "./cards/10ofclubs.png",
  },
  {
    category: "diamonds",
    card: "10",
    power: "10",
    img: "./cards/10ofdiamonds.png",
  },
  {
    category: "hearts",
    card: "10",
    power: "10",
    img: "./cards/10ofhearts.png",
  },
  {
    category: "spades",
    card: "10",
    power: "10",
    img: "./cards/10ofspades.png",
  },
  {
    category: "clubs",
    card: "J",
    power: "11",
    img: "./cards/jackofclubs.png",
  },
  {
    category: "diamonds",
    card: "J",
    power: "11",
    img: "./cards/jackofdiamonds.png",
  },
  {
    category: "hearts",
    card: "J",
    power: "11",
    img: "./cards/jackofhearts.png",
  },
  {
    category: "spades",
    card: "J",
    power: "11",
    img: "./cards/jackofspades.png",
  },
  {
    category: "clubs",
    card: "Q",
    power: "12",
    img: "./cards/queenofclubs.png",
  },
  {
    category: "diamonds",
    card: "Q",
    power: "12",
    img: "./cards/queenofdiamonds.png",
  },
  {
    category: "hearts",
    card: "Q",
    power: "12",
    img: "./cards/queenofhearts.png",
  },
  {
    category: "spades",
    card: "Q",
    power: "12",
    img: "./cards/queenofspades.png",
  },
  {
    category: "clubs",
    card: "K",
    power: "13",
    img: "./cards/kingofclubs.png",
  },
  {
    category: "diamonds",
    card: "K",
    power: "13",
    img: "./cards/kingofdiamonds.png",
  },
  {
    category: "hearts",
    card: "K",
    power: "13",
    img: "./cards/kingofhearts.png",
  },
  {
    category: "spades",
    card: "K",
    power: "13",
    img: "./cards/kingofspades.png",
  },
  {
    category: "clubs",
    card: "A",
    power: "14",
    img: "./cards/aceofclubs.png",
  },
  {
    category: "diamonds",
    card: "A",
    power: "14",
    img: "./cards/aceofdiamonds.png",
  },
  {
    category: "hearts",
    card: "A",
    power: "14",
    img: "./cards/aceofhearts.png",
  },
  {
    category: "spades",
    card: "A",
    power: "14",
    img: "./cards/aceofspades.png",
  },
];
